# Generated by Django 4.0 on 2024-11-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='カテゴリ'),
        ),
    ]
